# Generated by Django 4.1.2 on 2022-10-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
