# Generated by Django 4.1.1 on 2022-10-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_alter_hero_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
