# Generated by Django 4.1.1 on 2022-10-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_hero_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
