# Generated by Django 4.1.2 on 2022-10-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_hero_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
