# Generated by Django 4.1.2 on 2022-10-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
