# Generated by Django 4.1.2 on 2022-10-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Team',
        ),
    ]
