# Generated by Django 4.1.2 on 2022-10-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_team_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
        migrations.AddField(
            model_name='hero',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
